apiVersion: batch/v1
kind: Job
metadata:
  name: split
spec:
  template:
    spec:
      containers:
      - name: split
        image: rafaelxokito/neuralnetnexussplit:latest
      restartPolicy: Never
  backoffLimit: 4