version: '3.8'

services:
  client:
    image: frontend
    build: ./client
    environment:
      - SERVER_URI=http://localhost:3001
      - SOCKET_URI=ws://localhost:3002
    ports:
      - "3000:8090"

  api-server:
    image: backend
    build: ./Backend
    environment:
      - DATABASE_URI=database
    ports:
      - "3001:3001"

  bucket:
    image: bucket
    build: ./bucket
    ports:
      - "3003:3003"
    volumes:
      - ./bucket/datasets:/usr/app/datasets
      - ./bucket/models:/usr/app/models

  socket-server:
    image: socket-server
    build: ./socket-server
    ports:
      - "3002:3002"

  traindummy:
    image: traindummy
    build: ./traindummy
    environment:
      - WSSERVER=socket-server

  database:
    image: mongo
    ports:
      - "27017:27017"