version: '3.8'

services:
  client:
    image: frontend
    build: ./client
    environment:
      - SERVER_URI=http://localhost:3001
      - SOCKET_URI=http://localhost:3002
    ports:
      - "3000:8080"

  api-server:
    image: backend
    build: ./Backend
    environment:
      - DATABASE_URI=database
    ports:
      - "3001:3001"
    volumes:
      - ./Backend/datasets:/usr/app/datasets
      - ./Backend/models:/usr/app/models

  socket-server:
    image: socket-server
    build: ./socket-server
    ports:
      - "3002:3002"

  database:
    image: mongo
    ports:
      - "27017:27017"