version: '3.8'

services:
  client:
    image: frontend
    build: ./Frontend
    environment:
      - SERVER_URI=http://localhost:3001
    ports:
      - "3000:3000"

  api-server:
    image: backend
    build: ./Backend
    environment:
      - DATABASE_URI=database
    ports:
      - "3001:3001"
    volumes:
      - ./Backend/datasets:/usr/app/datasets
      - ./Backend/models:/usr/app/models

  database:
    image: mongo
    ports:
      - "27017:27017"