apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mongo-statefulset
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50