apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: backend
data:
  # property-like keys; each key maps to a simple value
  MONGODB_CONNECTIONSTRING: "mongodb://mongo-service.backend.svc.cluster.local:27017/neuralnetnexus"
  GCP_PROJECT_ID: "neuralnetnexus"
  BUCKET_NAME: "neuralnetnexus-bucket"