apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: platform
data:
  # property-like keys; each key maps to a simple value
  MONGODB_CONNECTIONSTRING: "mongodb://root:root@mongo-service.backend.svc.cluster.local:27017"