apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  # property-like keys; each key maps to a simple value
  MONGODB_CONNECTIONSTRING: "mongodb+srv://admin:admin@nexusdatabase.ggnrqr6.mongodb.net/"
  GCP_PROJECT_ID: "neuralnetnexus"
  BUCKET_NAME: "neuralnetnexus-bucket"