apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-datasets
  namespace: backend
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 30Gi