apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
  namespace: backend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 15Gi
