apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-models
  namespace: backend
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 15Gi