apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      hostNetwork: true
      containers:
      - name: backend
        image: docker.io/rafaelxokito/neuralnetnexusbackend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        volumeMounts:
          - name: datasets-data
            mountPath: /usr/app/datasets
          - name: models-data
            mountPath: /usr/app/models
        env:
        - name: MONGODB_CONNECTION
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: MONGODB_CONNECTIONSTRING
      nodeSelector:
        kubernetes.io/role: platform
      volumes:
        - name: datasets-data
          persistentVolumeClaim:
            claimName: pvc-datasets
        - name: models-data
          persistentVolumeClaim:
            claimName: pvc-models