apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/rafaelxokito/neuralnetnexusfrontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      nodeSelector:
        kubernetes.io/role: platform
        