apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      hostNetwork: true
      containers:
      - name: frontend
        image: docker.io/rafaelxokito/neuralnetnexusfrontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
        env:
        - name: SERVER_URI
          value: "http://backend-service:3001"
        - name: SOCKET_URI
          value: "http://socket-service:3002"
      nodeSelector:
        kubernetes.io/role: platform
        