apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-deployment
  namespace: neuralnetnexus
spec:
  selector:
    matchLabels:
      app: socketserver
  replicas: 1
  template:
    metadata:
      labels:
        app: socketserver
    spec:
      containers:
      - name: socketserver
        image: docker.io/rafaelxokito/neuralnetnexussocketserver:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
      nodeSelector:
        kubernetes.io/role: platform
        