apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-deployment
spec:
  selector:
    matchLabels:
      app: socketserver
  template:
    metadata:
      labels:
        app: socketserver
    spec:
      containers:
      - name: socketserver
        image: docker.io/rafaelxokito/neuralnetnexussocketserver:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        resources:
          limits:
            cpu: 2000m
            memory: 1000Mi
      nodeSelector:
        kubernetes.io/role: platform
        