apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: neuralnetnexus
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
